/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;
import java.sql.SQLException;

import org.example.persistence.ConnectionUtil;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        try (Connection connection = ConnectionUtil.getConnection()) {
            System.out.println("Conectou");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
